BEGIN;

CREATE TABLE IF NOT EXISTS public.instagram_shares (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_token varchar(64) NOT NULL UNIQUE,
    sender_id varchar(255) NOT NULL,
    source_url text NOT NULL DEFAULT '',
    title text NOT NULL DEFAULT '',
    places_json text NOT NULL DEFAULT '[]',
    claimed_by_user_id text,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_instagram_shares_sender_id
    ON public.instagram_shares (sender_id);
CREATE INDEX IF NOT EXISTS ix_instagram_shares_claimed_by_user_id
    ON public.instagram_shares (claimed_by_user_id);
CREATE INDEX IF NOT EXISTS ix_instagram_shares_expires_at
    ON public.instagram_shares (expires_at);

COMMIT;
