name: Sple Backend Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: sple-backend
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # --- 여기서부터 환경변수 반영 로직 추가 ---

      - name: Download current Task Definition
        run: |
          aws ecs describe-task-definition --task-definition default-sple-backend-6440 --query taskDefinition > task-definition.json

      - name: Fill in the new image ID and Environment Variables in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: sple-backend # ECS 컨테이너 이름 확인 필요
          image: ${{ steps.login-ecr.outputs.registry }}/sple-backend:latest
          environment-variables: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: sple-backend-6440
          cluster: default
          wait-for-service-stability: true
